### ISSUE TITLE
Scructs.tt not generating table schema names in Structs.cs using MySQL.ttinclude

### ISSUE THREAD

**Issue by ghost** [subsonic/SubSonic-3.0-Templates#1]
Hi,

Structs.tt isnt generating the table schema name when using MySQL.ttinclude.  Line 28:

SchemaName = "<#=tbl.Schema#>";

The error reads: 

" Error 3 Running transformation: System.ArgumentNullException: Value cannot be null. Parameter name: objectToConvert at Microsoft.VisualStudio.TextTemplating.ToStringHelper.ToStringWithCulture(Object objectToConvert) at Microsoft.VisualStudio.TextTemplating3BD02BC645E0D86C85EB7201F039F235.GeneratedTextTransformation.TransformText()....."
## This is the code being generated in Structs.cs:

```
/// <summary>
/// Table: _companies
/// Primary Key: ID
/// </summary>

public class _companiesTable: DatabaseTable {

    public _companiesTable(IDataProvider provider):base("_companies",provider){
        ClassName = "_company";
        SchemaName = "
```

---

I have tried using MySQL connector 6.04 and 5.1, and mysql server versions 5.067 and 5.1.33 with the same results.  All using Vista x64

Bob

**Comment by ghost** [comment]
I've also tried changing the tablename to remove the underscore - no change.

**Comment by robconery** [comment]
Fixed - thank you!
