### ISSUE TITLE
LinqTemplates / Classes.tt does not use ExcludeTables

### ISSUE THREAD

**Issue by hheexx** [subsonic/SubSonic-3.0-Templates#11]
I added
 <#   if(ExcludeTables.Contains(tbl.Name)) continue;#>

as the first line in foreach and that fixed the problem....

**Comment by robconery** [comment]
Where is this?

**Comment by robconery** [comment]
closing.

**Comment by hheexx** [comment]
LinqTemplates/Classes.tt
