### ISSUE TITLE
sqlite provider broken

### ISSUE THREAD

**Issue by zodman** [subsonic/SubSonic-3.0-Templates#16]
Error   8   Compiling transformation: El control no puede pasar explícitamente de una etiqueta case a otra ('case "integer":') f:\Trabajo\Visual Studio 2008\Projects\ConsoleApplication2\ConsoleApplication2\SQLite.ttinclude 80  3   

```
    case "long":
    case "integer":
        sysType= "long";
                    //need a break here!
    case "guid":
        sysType=  "Guid";
         break;
```

**Comment by funky81** [comment]
Hi zodman, to fix this, you can checkout my Subsonic3 templates fork while the bug fixed being checked and push into Subsonic3 templates master,

**Comment by erickemp** [comment]
Thanks funky81... Your template updates have been pushed...

**Comment by funky81** [comment]
Thanks erickemp
