### ISSUE TITLE
IsNew is true after loading with SingleOrDefault

### ISSUE THREAD

**Issue by jcoenen** [subsonic/SubSonic-3.0-Templates#3]
To recreate
var test = Category.LoadSingleOrDefault(c=>c.CategoryId=1);
Assert.IsFalse(test.IsNew());

To fix (sorry unable to get github working through corp firewall/proxy so unable to fork/fix/pull)

Add this line to both SingleOrDefault() overloads
single.SetIsNew(false);

**Comment by robconery** [comment]
FIXED: isNew should be false after loading with SingleOrDefault. Closed by f27205b098ebd0ff7c07454597bde7c45257e3a7
