### ISSUE TITLE
Username provided to Update() or Add() gets whiped out

### ISSUE THREAD

**Issue by jcoenen** [subsonic/SubSonic-3.0-Templates#4]
Update(int username, IDataProvider provider) 
and 
Add(int username, IDataProvider provider)

both call Update/Add(IDataProvider provider)

which promptly sets ModifiedBy/CreatedBy to Environment.UserName overwriting whatever was passed in to the other overload.

**Comment by robconery** [comment]
Fixed issue with Update() in AR template overriding a set username. Closed by ee5c4289ddbae3220f6ac25a345c1ccf4ff916df
