### ISSUE TITLE
MySQL.ttincludes Timestamp as String

### ISSUE THREAD

**Issue by InnerSphere** [subsonic/SubSonic-3.0-Templates#5]
I'm Using MySQL and ActiveRecord : 
Attempts to run linq queries on tables with Timestamp columns results in: Object of type 'System.DateTime' cannot be converted to type 'System.String'. 

If I change the following:
(Line 88)
    case "smalldatetime":
    case "datetime":
    sysType=  "DateTime";
    break;

to

```
case "smalldatetime":
case "datetime":
case "timestamp":
sysType=  "DateTime";
break;
```

And

(line 163)
    case "timestamp":
    return DbType.Binary;
to
    case "timestamp":
    return DbType.DateTime;

Seems to fix the problem

**Comment by robconery** [comment]
FIXED Issue 5 - MySQL timestamp not being recognized at valid date. Closed by 1537f96e57960ea9738ce82d09942e7ba99c1c45
