### ISSUE TITLE
Compiler warning in code generated by ActiveRecord.tt

### ISSUE THREAD

**Issue by lukesampson** [subsonic/SubSonic-3.0-Templates#6]
Compiler warning is "The field '[ClassName].TestItems' is never used".

Does this need to be initialised to an empty IList&lt;T&gt;, or removed altogether? Am I right, it seems to have been superseded by the TestRepository&lt;T&gt;?

**Comment by robconery** [comment]
Fixed issue with compiler warning for TestItems not being used. Closed by f943d5c5a5ca7f085f87a9ab837bd10e8c443d7d
