### ISSUE TITLE
Mysql record update very wrong.

### ISSUE THREAD

**Issue by hheexx** [subsonic/SubSonic-3.0-Templates#9]
I have this table on mysql 5.0.51 server:
CREATE TABLE  `ceger_dev`.`eo_crawler_shops` (
  `ID` int(10) unsigned NOT NULL auto_increment,
  `ShopName` varchar(128) NOT NULL,
  `NextCrawl` datetime NOT NULL COMMENT 'setuje se kad se zavrsi crawl',
  `CrawlInProgress` tinyint(1) NOT NULL default '0',
  `LastCrawl` datetime default NULL COMMENT 'setuje se kad krene crawl',
  PRIMARY KEY  (`ID`),
  UNIQUE KEY `Index_ShopName` (`ShopName`)
) ENGINE=InnoDB AUTO_INCREMENT=19 DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;

When I try to update table with this code:

```
    Dim siteName = "Example.com"
    Dim context As New ssDAL.ceger_devDB()
    Dim dbShop = (From shop In context.eo_crawler_shops _
      Where shop.ShopName.Equals(siteName)).First()
    dbShop.CrawlInProgress = True
    dbShop.LastCrawl = DateTime.UtcNow()
    dbShop.Save()
```

Last crawl gets set to : 0000-00-00 00:00:00  and CrawlInProgress stays at false.

**Comment by robconery** [comment]
I don't know what you're saying here.

**Comment by hheexx** [comment]
When I execute quoted code on quoted table expected result is that CrawlInProgress field is set tu True and LastCrawl field to current time. Right ?
Insted of that CrawlInProgress field stays at False and  LastCrawl field is set to invalid time (for .net)  : 0000-00-00 00:00:00

**Comment by robconery** [comment]
I still can't tell what's happening here - but I did make some changes to the way args are passed to the commands. Please grab latest source.
